"use client";

import { jsPDF } from "jspdf";
import { Button } from "@/components/ui/button";
import type { CalendarEventRow } from "@/components/calendar/calendar-month";

type CalendarView = "month" | "list" | "year";

interface CalendarExportButtonProps {
  view: CalendarView;
  year: number;
  month: number;
  events: CalendarEventRow[];
  listEvents: CalendarEventRow[];
}

function formatDateLabel(iso: string | null | undefined) {
  if (!iso) return "";
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return "";
  return d.toLocaleDateString(undefined, {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

function monthName(year: number, month: number) {
  return new Date(year, month - 1, 1).toLocaleString("en-US", {
    month: "long",
  });
}

export function CalendarExportButton({
  view,
  year,
  month,
  events,
  listEvents,
}: CalendarExportButtonProps) {
  async function handleExport() {
    const doc = new jsPDF({ orientation: "portrait", unit: "pt", format: "letter" });
    const pageWidth = doc.internal.pageSize.getWidth();

    const headerY = 40;
    const titleY = 70;
    const contentStartY = 100;

    const now = new Date();
    const generatedAt = now.toLocaleString();

    // Header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor("#3D3D3D");
    doc.text("MyVow Parenting", 40, headerY);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor("#6B6B6B");
    doc.text(`Generated: ${generatedAt}`, pageWidth - 40, headerY, { align: "right" });

    // Title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor("#3D3D3D");
    let title = "";
    if (view === "month") {
      title = `${monthName(year, month)} ${year} – Month view`;
    } else if (view === "list") {
      title = `${monthName(year, month)} ${year} – List view`;
    } else {
      title = `${year} – Year overview`;
    }
    doc.text(title, 40, titleY);

    doc.setDrawColor("#E8E4DC");
    doc.line(40, titleY + 8, pageWidth - 40, titleY + 8);

    if (view === "month") {
      exportMonth(doc, contentStartY, year, month, events);
    } else if (view === "list") {
      exportList(doc, contentStartY, listEvents);
    } else {
      exportYear(doc, contentStartY, year, events);
    }

    // Footer
    const footerY = doc.internal.pageSize.getHeight() - 40;
    doc.setFontSize(8);
    doc.setTextColor("#6B6B6B");
    doc.text(
      "Generated by MyVow Parenting — Confidential",
      pageWidth / 2,
      footerY,
      { align: "center" }
    );

    doc.save(
      view === "month"
        ? `calendar-${year}-${String(month).padStart(2, "0")}.pdf`
        : view === "year"
          ? `calendar-${year}.pdf`
          : `calendar-list-${year}-${String(month).padStart(2, "0")}.pdf`
    );
  }

  return (
    <Button
      type="button"
      size="sm"
      className="h-8 rounded-full text-xs bg-[#7B9E87] hover:bg-[#6A8A78] text-white"
      onClick={() => void handleExport()}
    >
      Export PDF
    </Button>
  );
}

function exportMonth(
  doc: jsPDF,
  startY: number,
  year: number,
  month: number,
  events: CalendarEventRow[]
) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const gridLeft = 40;
  const gridRight = pageWidth - 40;
  const gridWidth = gridRight - gridLeft;
  const colWidth = gridWidth / 7;
  const rowHeight = 40;

  const firstDay = new Date(year, month - 1, 1).getDay(); // 0=Sun
  const daysInMonth = new Date(year, month, 0).getDate();

  const eventsByDay = new Map<number, CalendarEventRow[]>();
  for (const e of events) {
    const d = new Date(e.start_time);
    if (Number.isNaN(d.getTime())) continue;
    if (d.getFullYear() !== year || d.getMonth() + 1 !== month) continue;
    const day = d.getDate();
    if (!eventsByDay.has(day)) eventsByDay.set(day, []);
    eventsByDay.get(day)!.push(e);
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor("#6B6B6B");
  const headers = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
  headers.forEach((h, i) => {
    doc.text(h, gridLeft + colWidth * i + colWidth / 2, startY, {
      align: "center",
    });
  });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor("#3D3D3D");

  let day = 1;
  let row = 1;
  while (day <= daysInMonth) {
    for (let col = 0; col < 7 && day <= daysInMonth; col++) {
      const cellIndex = (row - 1) * 7 + col;
      if (cellIndex < firstDay) continue;
      const x = gridLeft + colWidth * col;
      const y = startY + 10 + rowHeight * row;

      doc.setDrawColor("#E8E4DC");
      doc.rect(x, y - rowHeight + 5, colWidth, rowHeight, "S");

      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor("#3D3D3D");
      doc.text(String(day), x + 4, y - rowHeight + 16);

      const dayEvents = eventsByDay.get(day) ?? [];
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor("#5B7A52");
      let offsetY = y - rowHeight + 26;
      for (const ev of dayEvents.slice(0, 3)) {
        const label = ev.title ?? "(event)";
        const truncated =
          label.length > 24 ? `${label.slice(0, 21)}…` : label;
        doc.text(truncated, x + 4, offsetY);
        offsetY += 10;
      }

      day += 1;
    }
    row += 1;
  }
}

function exportList(doc: jsPDF, startY: number, events: CalendarEventRow[]) {
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = startY;

  const sorted = [...events].sort((a, b) =>
    String(a.start_time).localeCompare(String(b.start_time))
  );

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);

  if (sorted.length === 0) {
    doc.text("No events in this range.", 40, y);
    return;
  }

  for (const ev of sorted) {
    const dateLabel = formatDateLabel(ev.start_time);
    const category = ev.event_type ?? "";
    const childName = ev.child_name ?? "";
    const title = ev.title ?? "(event)";

    const line = `${dateLabel}  —  ${title}`.trim();
    doc.setTextColor("#3D3D3D");
    doc.text(line, 40, y);

    const meta: string[] = [];
    if (category) meta.push(category);
    if (childName) meta.push(childName);
    if (meta.length > 0) {
      doc.setTextColor("#6B6B6B");
      doc.setFontSize(8);
      doc.text(meta.join(" • "), 40, y + 11);
      y += 24;
      doc.setFontSize(9);
    } else {
      y += 18;
    }

    if (y > doc.internal.pageSize.getHeight() - 60) {
      doc.addPage();
      y = startY;
    }
  }
}

function exportYear(
  doc: jsPDF,
  startY: number,
  year: number,
  events: CalendarEventRow[]
) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const left = 40;
  const colWidth = (pageWidth - 80) / 3;
  const rowHeight = 90;

  const eventKeys = new Set<string>();
  for (const e of events) {
    const d = new Date(e.start_time);
    if (Number.isNaN(d.getTime())) continue;
    if (d.getFullYear() !== year) continue;
    const key = `${d.getMonth() + 1}-${d.getDate()}`;
    eventKeys.add(key);
  }

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);

  for (let m = 1; m <= 12; m++) {
    const col = (m - 1) % 3;
    const row = Math.floor((m - 1) / 3);
    const x = left + colWidth * col;
    const y = startY + rowHeight * row;

    const name = new Date(year, m - 1, 1).toLocaleString("en-US", {
      month: "short",
    });
    doc.setFont("helvetica", "bold");
    doc.setTextColor("#3D3D3D");
    doc.text(`${name}`, x, y);

    doc.setFont("helvetica", "normal");
    doc.setTextColor("#5B7A52");

    const daysInMonth = new Date(year, m, 0).getDate();
    let line = "";
    let lineY = y + 14;
    for (let d = 1; d <= daysInMonth; d++) {
      const key = `${m}-${d}`;
      if (eventKeys.has(key)) {
        line += "•";
      } else {
        line += ".";
      }
      if (d % 14 === 0 || d === daysInMonth) {
        doc.text(line, x, lineY);
        line = "";
        lineY += 10;
      }
    }
  }
}

